# Generated by Django 4.1.5 on 2023-06-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item_description',
        ),
    ]
