# Generated by Django 4.1.5 on 2023-06-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoice_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='item_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
