# Generated by Django 4.1.5 on 2023-06-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='zipcode',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
